
/// ===== LOGS ==== \\\\

export const GET_LOGS_REQUEST = 'GET_LOGS_REQUEST';
export const GET_LOGS_SUCCESS = 'GET_LOGS_SUCCESS';
export const GET_LOGS_ERROR = 'GET_LOGS_ERROR';


//// === LOADER === \\\
export const LOADER = 'LOADER'
/// ==== DEVICE ==== \\\

export const GET_DEVICE_REQUEST = 'GET_DEVICE_REQUEST';
export const GET_DEVICE_SUCCESS = 'GET_DEVICE_SUCCESS';
export const GET_DEVICE_ERROR = 'GET_DEVICE_ERROR';
export const GET_DEVICE_LIST_REQUEST = 'GET_DEVICE_LIST_REQUEST';
export const GET_DEVICE_LIST_SUCCESS = 'GET_DEVICE_LIST_SUCCESS';
export const GET_DEVICE_LIST_ERROR = 'GET_DEVICE_LIST_ERROR';
export const GET_DEVICE_EXCEL_EXPORT_REQUEST = 'GET_DEVICE_EXCEL_EXPORT_REQUEST';
export const GET_DEVICE_EXCEL_EXPORT_SUCCESS = 'GET_DEVICE_EXCEL_EXPORT_SUCCESS';
export const GET_DEVICE_EXCEL_EXPORT_ERROR = 'GET_DEVICE_EXCEL_EXPORT_ERROR';
export const ADD_DEVICE_REQUEST = 'ADD_DEVICE_REQUEST';
export const ADD_DEVICE_SUCCESS = 'ADD_DEVICE_SUCCESS';
export const ADD_DEVICE_ERROR = 'ADD_DEVICE_ERROR';
export const UPDATE_DEVICE_REQUEST = 'UPDATE_DEVICE_REQUEST';
export const UPDATE_DEVICE_SUCCESS = 'UPDATE_DEVICE_SUCCESS';
export const UPDATE_DEVICE_ERROR = 'UPDATE_DEVICE_ERROR';
export const HIDE_DEVICE_REQUEST = 'HIDE_DEVICE_REQUEST';
export const HIDE_DEVICE_SUCCESS = 'HIDE_DEVICE_SUCCESS';
export const HIDE_DEVICE_ERROR = 'HIDE_DEVICE_ERROR'

//// ===== USERS ==== \\\\\

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';

export const GET_USERS_LIST_REQUEST = 'GET_USERS_LIST_REQUEST';
export const GET_USERS_LIST_SUCCESS = 'GET_USERS_LIST_SUCCESS';
export const GET_USERS_LIST_ERROR = 'GET_USERS_LIST_ERROR';

export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';

export const BLOCK_USER_REQUEST = 'BLOCK_USER_REQUEST';
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS';
export const BLOCK_USER_ERROR = 'BLOCK_USER_ERROR';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_ERORR = 'UPDATE_USER_ERORR';




/// ==== AUTH ==== \\\\

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

/// ==== shocommands ==== \\\

export const SHOWCOMMAND_GPON_REQUEST = 'SHOWCOMMAND_GPON_REQUEST';
export const SHOWCOMMAND_GPON_SUCCESS = 'SHOWCOMMAND_GPON_SUCCESS';
export const SHOWCOMMAND_GPON_ERROR = 'SHOWCOMMAND_GPON_ERROR';

export const SHOWCOMMAND_DSL_REQUEST = 'SHOWCOMMAND_DSL_REQUEST';
export const SHOWCOMMAND_DSL_SUCCESS = 'SHOWCOMMAND_DSL_SUCCESS';
export const SHOWCOMMAND_DSL_ERROR = 'SHOWCOMMAND_DSL_ERROR';

export const SHOWCOMMAND_DHCP_LOG_REQUEST = 'SHOWCOMMAND_DHCP_LOG_REQUEST';
export const SHOWCOMMAND_DHCP_LOG_SUCCESS = 'SHOWCOMMAND_DHCP_LOG_SUCCESS';
export const SHOWCOMMAND_DHCP_LOG_ERROR = 'SHOWCOMMAND_DHCP_LOG_ERROR';

export const SHOWCOMMAND_DHCP_COA_LOG_REQUEST = 'SHOWCOMMAND_DHCP_COA_LOG_REQUEST';
export const SHOWCOMMAND_DHCP_COA_LOG_SUCCESS = 'SHOWCOMMAND_DHCP_COA_LOG_SUCCESS';
export const SHOWCOMMAND_DHCP_COA_LOG_ERROR = 'SHOWCOMMAND_DHCP_COA_LOG_ERROR';

export const SHOW_SERVICE_PORT_BIND_CABSAT_REQUEST = 'SHOW_SERVICE_PORT_BIND_CABSAT_REQUEST';
export const SHOW_SERVICE_PORT_BIND_CABSAT_SUCCESS = 'SHOW_SERVICE_PORT_BIND_CABSAT_SUCCESS';
export const SHOW_SERVICE_PORT_BIND_CABSAT_ERROR = 'SHOW_SERVICE_PORT_BIND_CABSAT_ERROR';

export const SET_SERVICE_PORT_BIND_CABSAT_REQUEST = 'SET_SERVICE_PORT_BIND_CABSAT_REQUEST';
export const SET_SERVICE_PORT_BIND_CABSAT_SUCCESS = 'SET_SERVICE_PORT_BIND_CABSAT_SUCCESS';
export const SET_SERVICE_PORT_BIND_CABSAT_ERROR = 'SET_SERVICE_PORT_BIND_CABSAT_ERROR';

export const SET_SERVICE_PORT_CABSAT_REQUEST = 'SET_SERVICE_PORT_CABSAT_REQUEST';
export const SET_SERVICE_PORT_CABSAT_SUCCESS = 'SET_SERVICE_PORT_CABSAT_SUCCESS';
export const SET_SERVICE_PORT_CABSAT_ERROR = 'SET_SERVICE_PORT_CABSAT_ERROR';

export const SET_COMMANDS_GPON_HUAWEI_SERVICE_PORT_REQUEST = "SET_COMMANDS_GPON_HUAWEI_SERVICE_PORT_REQUEST";
export const SET_COMMANDS_GPON_HUAWEI_SERVICE_PORT_SUCCESS = 'SET_COMMANDS_GPON_HUAWEI_SERVICE_PORT_SUCCESS';
export const SET_COMMANDS_GPON_HUAWEI_SERVICE_PORT_ERROR = 'SET_COMMANDS_GPON_HUAWEI_SERVICE_PORT_ERROR';

export const SET_COMMANDS_GPON_ZTE_SERVICE_PORT_REQUEST = 'SET_COMMANDS_GPON_ZTE_SERVICE_PORT_REQUEST';
export const SET_COMMANDS_GPON_ZTE_SERVICE_PORT_SUCCESS = 'SET_COMMANDS_GPON_ZTE_SERVICE_PORT_SUCCESS';
export const SET_COMMANDS_GPON_ZTE_SERVICE_PORT_ERROR = 'SET_COMMANDS_GPON_ZTE_SERVICE_PORT_ERROR';

// ==== loader ===\\
export const LOADER_REQUEST = 'LOADER_REQUEST';
export const LOADER_SUCCESS = 'LOADER_SUCCESS'

export const ALERT = 'ALERT';


//// ====  AUTO FIND sn ==== \\\\
export const AUTOFIND_SN_REQUEST = 'AUTOFIND_SN_REQUEST';
export const AUTOFIND_SN_SUCCESS = 'AUTOFIND_SN_SUCCESS';
export const AUTOFIND_SN_ERROR = 'AUTOFIND_SN_ERROR';

//// ===== AUTO FIND position === \\\
export const AUTOFIND_REQUEST = 'AUTOFIND_REQUEST';
export const AUTOFIND_SUCCESS = 'AUTOFIND_SUCCESS';
export const AUTOFIND_ERROR = 'AUTOFIND_ERROR';

/// ==== mgc === \\\\

export const MGC_REQUEST = 'MGC_REQUEST';
export const MGC_SUCCESS = 'MGC_SUCCESS';
export const MGC_ERROR = 'MGC_ERROR';

/// ==== REMOVE MAC ==== \\\\\

export const REMOVE_MAC_REQUEST = 'REMOVE_MAC_REQUEST';
export const REMOVE_MAC_SUCCESS = 'REMOVE_MAC_SUCCESS';
export const REMOVE_MAC_ERROR = 'REMOVE_MAC_ERROR';



